[project]
name = "fas-swin"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "facenet-pytorch>=2.5.3",
    "numpy>=2.4.6",
    "opencv-python>=4.13.0.92",
    "scikit-learn>=1.8.0",
    "scipy>=1.17.1",
    "timm>=1.0.27",
    "torchvision>=0.27.0",
    "tqdm>=4.67.3",
]
